<<<<<<< HEAD
# Generated by Django 2.0.5 on 2018-06-26 01:35
=======
# Generated by Django 2.0.5 on 2018-07-15 14:05
>>>>>>> 备注

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='cdbus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500)),
                ('stopsnum', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=4, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500)),
                ('lng', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('line', models.CharField(default='', max_length=500)),
                ('district', models.CharField(default='', max_length=500)),
                ('center_distance', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
>>>>>>> 备注
            name='POIDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poiname', models.CharField(default='', max_length=500)),
                ('origintag', models.CharField(default='', max_length=500)),
                ('address', models.CharField(default='', max_length=500)),
                ('lng', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tags', models.CharField(default='', max_length=500)),
                ('distance', models.DecimalField(decimal_places=4, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='POIDetailTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subInfo.POIDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('lng', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('line', models.CharField(default='', max_length=500)),
                ('district', models.CharField(default='', max_length=500)),
                ('center_distance', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Stationname',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
>>>>>>> 备注
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='poidetailtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subInfo.Tag'),
        ),
        migrations.AddField(
            model_name='poidetail',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subInfo.Station'),
        ),
    ]
